# 项目基本配置
app:
  ## 应用名称
  app_name: GoApi
  ## 当前环境
  app_env: dev
  ## 用以生成链接
  app_url: http://127.0.0.1
  ## 应用服务端口
  app_port: 1234
  # pprof 分析 打开后可以分析堆栈调用，cpu占用
  app_pprof: true


# 数据库连接信息
database:
  connection: mysql
  host: 127.0.0.1
  port: 3306
  name: maccms
  username: root
  password: root
  prefix: mac_

# Redis 配置
redis:
  host: 127.0.0.1
  # 没有密码，默认留空
  password:
  # 端口号
  port: 6379
  # 默认用 0
  db: 0

# log 日志控制
log:
  # mysql debug 日志
  mysql_debug: true
  # mysql error 日志
  mysql_error: true
  # mysql warn 日志
  mysql_warn: true

# maccms 配置
maccms:
  site:
    site_name: "电影先生 - dyxs.site 在线 播放 观看"
    site_url: "dyxs.site"
    site_wapurl: "dyxs.site"
    site_keywords: "电影先生,最新电影,电影大全,影视大全,在线电影,免费电影,电影在线观看,最新电视剧,电影先生,在线播放,百度网盘,免费视频,在线视频,预告片,dyxs.site"
    site_description: "电影先生提供最新最快的视频分享数据-聚合全网影片，你想看的全都有！每天搜集互联网最新电影和电视剧，为广大用户免费提供无广告在线观看电影和电视剧服务，及时收录最新、最热、最全的电影大片,高清正版免费看。dyxs.site"
    site_icp: ""
    site_qq: ""
    site_email: "mail@dyxs.site"
    install_dir: "/"
    site_logo: ""
    site_waplogo: ""
    template_dir: "DYXS2"
    html_dir: "html"
    mob_status: "0"
    mob_template_dir: "DYXS2"
    mob_html_dir: "html"
    site_tj: |
      <script>
      var _hmt = _hmt || [];
      (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?f46a2caaf84b781dc103b13289d90383";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();
      </script>
      <script>let u="https:\/\/api.cgyx.tv:66",token="f7dd072abb9af17700b0b8a1bd8b8e1dc43e13838257436c31c30f4495aba5a79382ef3b36808ab90351f85de968be49838554c9b1e809e46631bdd330fc2189";var cltj = document.createElement("script");cltj.src = u + "\/tj\/tongji.js?v=1.3";var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(cltj,s);<\/script>
    site_status: "1"
    site_close_tip: "站点暂时关闭，请稍后访问"
    ads_dir: "ads"
    mob_ads_dir: "ads"

# seo相关配置参数
seo:
  bing:
    apikey: 1212121221212121212
  baidu:
    apikey:
  sogou:
    apikey:


# bark 通知配置
bark:
  url: https://api.day.app/
  key:
    mac: YaemvezPAqvc2ASewcP2KH
    iphone: nPuDoXfXsMpVrDaqU9to88
  logo: https://avatars.githubusercontent.com/u/135967790?s=400&u=0efb3cc947e9f0c2165c11f65f374524cb48915d&v=4

wechat:
  botUrl: http://localhost:8000
  guid: 68d4ebef-f854-3387-ab40-7832d51dab25
  BelongWx: xiaomg_zs